SampleMvcApp/Controllers/FirstExampleController.cs
using System;
using SampleMvcApp.Models;
using System.Web.Mvc;//This namespace contains all the classes and interfaces required for the MVC App Development. 
//Controller is simply a .NET Class that implements an interface called IController. however in our application, UR class will derived from a Class called Controller which contains the default implementations for IController
//URController -> Controller -> ControllerBase -> IController. 
//Some Apps will implement their own version of IController interface for customization and optimization purposes.
namespace SampleMvcApp.Controllers
{
    public class FirstExampleController : Controller
    {
        public string DisplayMessage()//Action is the term used for a public function of a Controller. 
        {
            string model = "My First MVC Project";
            return model;
        }

        public Employee DisplayEmployee()
        {
            var emp = new Employee { EmpAddress = "Bangalore", EmpID = 123, EmpName = "Phaniraj" };//create the model
            return emp;//HTTP is a text/string based protocol, any object U return will be converrted to string and displayed on the browser. 
        }

        public ViewResult Display()
        {
            var emp = new Employee { EmpAddress = "Bangalore", EmpID = 123, EmpName = "Phaniraj" };//create the model
            return View(emp);
        }
    }
}

SampleMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC Training", "DisplayMessage", "FirstExample", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Powered by ASP.NET MVC</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>